// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/calculate-packaging": {
            "get": {
                "description": "Calculate the best packaging option for a given number of items",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packaging"
                ],
                "summary": "Calculate order packaging",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Number of items",
                        "name": "items",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of packs",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/packaging.Pack"
                            }
                        }
                    },
                    "406": {
                        "description": "Invalid input",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "packaging.Pack": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "size": {
                    "$ref": "#/definitions/packaging.PackageSize"
                }
            }
        },
        "packaging.PackageSize": {
            "type": "integer",
            "enum": [
                250,
                500,
                1000,
                2000,
                5000
            ],
            "x-enum-varnames": [
                "Small"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
