definitions:
  packaging.Pack:
    properties:
      quantity:
        type: integer
        default: 1
      size:
        $ref: '#/definitions/packaging.PackageSize'
    type: object
  packaging.PackageSize:
    enum:
    - 250
    - 500
    - 1000
    - 2000
    - 5000
    type: integer
    x-enum-varnames:
    - Small
info:
  contact: {}
paths:
  /v1/calculate-packaging:
    get:
      consumes:
      - application/json
      description: Calculate the best packaging option for a given number of items
      parameters:
      - description: Number of items
        in: query
        minimum: 1
        name: items
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of packs
          schema:
            items:
              $ref: '#/definitions/packaging.Pack'
            type: array
        "406":
          description: Invalid input
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      summary: Calculate order packaging
      tags:
      - packaging
swagger: "2.0"
