definitions:
  list.Message:
    properties:
      content:
        type: string
      id:
        type: integer
      sent:
        type: boolean
      sent_at:
        type: string
      to:
        type: string
    type: object
  start_stop.startStopForm:
    properties:
      action:
        enum:
        - start
        - stop
        type: string
    required:
    - action
    type: object
info:
  contact: {}
paths:
  /messages/:
    get:
      consumes:
      - application/json
      description: Get all messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/list.Message'
            type: array
      summary: List messages
      tags:
      - messages
    patch:
      consumes:
      - application/json
      description: Update the status of the message engine
      parameters:
      - description: Action to start or stop the message engine
        in: body
        name: action
        required: true
        schema:
          $ref: '#/definitions/start_stop.startStopForm'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
        "406":
          description: Not Acceptable
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update message status
      tags:
      - messages
swagger: "2.0"
